project_id = "onwdhwuqehuakvtkakuk"

[functions.provision-tecnicos]
verify_jwt = false

[functions.tecnico-app]
verify_jwt = false

[functions.provision-portal-users]
verify_jwt = false

[functions.acesso-cpf]
verify_jwt = false
