
ALTER TABLE public.almoxarifado_carga
  ADD COLUMN IF NOT EXISTS cpf text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS matricula text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS funcao text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS setor text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS filial text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tipo text NOT NULL DEFAULT 'carga',
  ADD COLUMN IF NOT EXISTS responsavel_nome text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS anexo_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS anexo_nome text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS comprovante_url text NOT NULL DEFAULT '';
